users:
  - name: petert
    gecos: Peter T
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: users, sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "${PETERT_SSH_KEY_1}"
      - "${PETERT_SSH_KEY_2}"
    passwd: "${PETERT_PASSWORD_HASH}"
    lock_passwd: false
  - name: ansible
    gecos: ansible user
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: users, sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "${ANSIBLE_SSH_KEY_1}"
